0it [00:00, ?it/s]Traceback (most recent call last):
  File "/Users/aneeshaparajit/Desktop/new workspace/dqn-atari/agent.py", line 197, in <module>
    main()
  File "/Users/aneeshaparajit/Desktop/new workspace/dqn-atari/agent.py", line 130, in main
    m = DQNModel(obs_shape=env.env.observation_space.shape, n_actions=env.env.action_space.n, device=device, window_size=4)
TypeError: DQNModel.__init__() got an unexpected keyword argument 'device'